apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
  namespace: webapps
spec:
  hosts:
   - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 0
    - destination:
        host: reviews
        subset: v2
      weight: 50
    - destination:
        host: reviews
        subset: v3
      weight: 50
  retries:
    attempts: 3
    perTryTimeout: 2s
    retryOn: 5xx,connect-failure